// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { existsSync } from "fs";
import { defineConfig } from "prisma/config";

// Load .env.local if it exists (local dev with Vercel)
if (existsSync(".env.local")) {
  const { config } = require("dotenv");
  config({ path: ".env.local", override: true });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
